### ISSUE TITLE
你好， 当我执行python train.py DBloss 时候报错：

### ISSUE THREAD

**Issue by sk0829** [Roche/BalancedLossNLP#13]
你好， 当我执行python train.py DBloss 时候报错：
UserWarning: No audio backend is available.
eight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at ./berts\bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

**Comment by blessu** [comment]
您好，这实际上是一个警告（UserWarning），而不是报错。
正如这里第一个要点提到的，载入bert模型用于进一步训练时，看到这个 warning 是预期中的。
该提醒常用于避免模型载入后被直接拿来做预测，因为一些权重是新初始化（而非从预训练的检查点中初始化）的。

**Comment by sk0829** [comment]
> 您好，这实际上是一个警告（UserWarning），而不是报错。 正如这里第一个要点提到的，载入bert模型用于进一步训练时，看到这个 warning 是预期中的。 该提醒常用于避免模型载入后被直接拿来做预测，因为一些权重是新初始化（而非从预训练的检查点中初始化）的。

非常感谢您的回复，祝您生活愉快！
